name: Update build environment

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: tools/docker/build-env.Dockerfile
          tags: stabbles/pkg-example:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}