name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: stabbles/pkg-example:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build this package
        run: |
          echo $PWD ${GITHUB_WORKSPACE} $PATH
          /opt/spack/bin/spack -e ${GITHUB_WORKSPACE}/tools/environments/ci/spack.yaml install -v