name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: stabbles/pkg-example:latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup spack
        run: |
          /opt/spack/bin/spack --color=always -e ./tools/environments/ci/ repo add ./tools/spack
          /opt/spack/bin/spack --color=always -e ./tools/environments/ci/ concretize
      - name: Build
        run: |
          /opt/spack/bin/spack --color=always -e ./tools/environments/ci/ install -v
      - name: Run tests
        run: |
          /opt/spack/bin/spack --color=always -e ./tools/environments/ci/ build-env mypkg@main ^mpich -- ctest --output-on-failure