name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: stabbles/pkg-example:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build this package
        run: |
          /opt/spack/bin/spack -e ./tools/environments/ci/ repo add ./tools/spack
          /opt/spack/bin/spack -e ./tools/environments/ci/ install -v